# Generated by Django 5.1.3 on 2024-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Name of the device (e.g., ATMOS 41)', max_length=100)),
                ('sensor_name', models.CharField(help_text='Specific sensor name (e.g., Wind Speed, Air Temperature)', max_length=100)),
                ('sensor_sn', models.CharField(blank=True, help_text='Serial number of the sensor', max_length=100, null=True)),
                ('value', models.FloatField(help_text='Measured value')),
                ('units', models.CharField(help_text='Units of the measurement (e.g., °C, mm, m/s)', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='Timestamp of the measurement')),
                ('timestamp_utc', models.DateTimeField(help_text='UTC timestamp of the measurement')),
                ('precision', models.FloatField(blank=True, help_text='Precision of the measurement (if applicable)', null=True)),
                ('error_flag', models.BooleanField(default=False, help_text='Indicates if there was an error during measurement')),
                ('error_description', models.TextField(blank=True, help_text='Details of any error encountered', null=True)),
            ],
        ),
    ]
