# Generated by Django 5.1.3 on 2024-12-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('sensor_name', models.CharField(max_length=100)),
                ('sensor_sn', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('timestamp_utc', models.DateTimeField()),
                ('precision', models.FloatField(blank=True, null=True)),
                ('error_flag', models.BooleanField(default=False)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='allmeteo.weathermeasurement')),
            ],
        ),
    ]
