# Generated by Django 5.1.3 on 2024-12-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instrument',
            table='instruments',
        ),
    ]
