# Generated by Django 5.1.3 on 2024-12-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_instrument_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
