# Generated by Django 5.1.3 on 2025-01-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='sensors',
            field=models.ManyToManyField(related_name='stations', through='database.StationSensor', to='database.sensor'),
        ),
    ]
