# Generated by Django 5.1.3 on 2024-12-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_brand_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='lat_lng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
