# Generated by Django 5.1.3 on 2025-01-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.TextField(null=True),
        ),
    ]
