# Generated by Django 5.0.1 on 2025-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_bill_receipt_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('interval', models.IntegerField(default=60)),
            ],
            options={
                'get_latest_by': 'last_run',
            },
        ),
    ]
