# Generated by Django 5.1.3 on 2025-01-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
