# Generated by Django 5.1.3 on 2024-12-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_brand_serial_number_alter_instrument_lat_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
