# Generated by Django 5.1.3 on 2025-01-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_station_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
