# Generated by Django 5.1.3 on 2025-01-27 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_user_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(unique=True)),
                ('token_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiAccessKeyStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='APIAccessToken',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='apiaccesskey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiaccesskeystation',
            name='api_access_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.apiaccesskey'),
        ),
        migrations.AddField(
            model_name='apiaccesskeystation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.station'),
        ),
        migrations.AddField(
            model_name='apiaccesskey',
            name='stations',
            field=models.ManyToManyField(through='database.ApiAccessKeyStation', to='database.station'),
        ),
        migrations.AlterUniqueTogether(
            name='apiaccesskeystation',
            unique_together={('api_access_key', 'station')},
        ),
    ]
