# Generated by Django 5.1.6 on 2025-03-28 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_merge_20250303_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_path', models.CharField(max_length=255)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('response_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xml', 'XML')], default='json', max_length=10)),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='database.apiaccesskey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', '-created_at'], name='api_key_usa_api_key_a5eccf_idx'), models.Index(fields=['user', '-created_at'], name='api_key_usa_user_id_d20ac3_idx')],
            },
        ),
    ]
