# Generated by Django 5.1.3 on 2025-01-27 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_apiaccesskey_apiaccesskeystation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_access_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_key', to='database.apiaccesskey'),
        ),
    ]
