# Generated by Django 5.1.6 on 2025-04-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_apikeyusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyusagelog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
