# Generated by Django 5.1.6 on 2025-05-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_stationhealthlog_station_hea_station_9c13dd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stationhealthlog',
            name='station_hea_station_9c13dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='stationhealthlog',
            name='station_hea_created_18b9ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='stationhealthlog',
            name='station_hea_connect_f4d884_idx',
        ),
    ]
