# Generated by Django 5.1.6 on 2025-05-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_stationhealthlog_station_hea_station_9c13dd_idx_and_more'),
        ('database', '0020_stationhealthlog_indexes'),
    ]

    operations = [
    ]
