# Generated by Django 5.1.6 on 2025-05-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_merge_20250507_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationhealthlog',
            name='battery_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='stationhealthlog',
            name='connectivity_status',
            field=models.CharField(default='No Data', max_length=50),
        ),
        migrations.AddIndex(
            model_name='stationhealthlog',
            index=models.Index(fields=['station_id', '-created_at'], name='idx_station_health_created'),
        ),
        migrations.AddIndex(
            model_name='stationhealthlog',
            index=models.Index(fields=['connectivity_status'], name='idx_connectivity_status'),
        ),
    ]
