# Generated by Django 5.1.6 on 2025-08-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0022_alter_stationhealthlog_battery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="flag",
            field=models.BooleanField(
                default=True,
                help_text="Data validation flag: True if data is within acceptable range, False if validation failed",
            ),
        ),
    ]
