# Generated by Django 5.2.5 on 2025-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0023_measurement_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="decommissioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Decommissioned", "Decommissioned"),
                    ("Maintenance", "Maintenance"),
                    ("Offline", "Offline"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
