# Generated by Django 5.2.5 on 2025-08-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0024_station_decommissioned_at_station_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensors",
                to="database.brand",
            ),
        ),
    ]
