# Generated by Django 5.2.5 on 2025-08-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0025_add_brand_to_sensors"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apiaccesskey",
            index=models.Index(
                fields=["user", "expires_at"], name="api_access__user_id_f0f85e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesskey",
            index=models.Index(fields=["uuid"], name="api_access__uuid_564f39_idx"),
        ),
        migrations.AddIndex(
            model_name="apiaccesskey",
            index=models.Index(
                fields=["created_at"], name="api_access__created_a476b4_idx"
            ),
        ),
    ]
