# Generated by Django 5.2.5 on 2025-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0026_apiaccesskey_api_access__user_id_f0f85e_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apiaccesskey",
            name="api_access__user_id_f0f85e_idx",
        ),
        migrations.RemoveIndex(
            model_name="apiaccesskey",
            name="api_access__uuid_564f39_idx",
        ),
        migrations.RemoveIndex(
            model_name="apiaccesskey",
            name="api_access__created_a476b4_idx",
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["status"], name="stations_status_b234b5_idx"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["brand"], name="stations_brand_i_f97da6_idx"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["name"], name="stations_name_edbe15_idx"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["installation_date"], name="stations_install_a78f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["status", "brand"], name="stations_status_76c430_idx"
            ),
        ),
    ]
