# Generated by Django 5.1.3 on 2025-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0027_add_station_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiaccesskey",
            name="is_perpetual",
            field=models.BooleanField(default=False),
        ),
    ]
