# Generated by Django 5.1.3 on 2025-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0029_plans"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Plans",
            new_name="Plan",
        ),
        migrations.AlterField(
            model_name="apiaccesskey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="package",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Yearly", "Yearly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
