# Generated by Django 5.1.3 on 2025-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0030_rename_plans_plan_alter_apiaccesskey_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
