# Generated by Django 5.1.3 on 2025-09-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0031_alter_user_subscription_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="package",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
