# Generated by Django 5.1.3 on 2024-12-08 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_instrument_table'),
        ('paws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='The instrument associated with this measurement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='database.instrument'),
        ),
    ]
